/**
 * Methodology v1 — Human-approved baseline (Phase 2A).
 * This is a FROZEN baseline: model must NOT auto-modify v1.
 * Changes go through Material → MethodologyCandidate → Human Review → New Version.
 * Mirror file: config/methodology-v1.json (human-editable source).
 *
 * B3: each dimension carries two kinds of data —
 *   - Research Framework (what to research): key/name/.../unknownCondition
 *   - Evaluation Policy   (how it is judged) : weight + criticality
 * Aggregation Policy (12→7) is NOT part of v1 (later phase).
 */

import type { MethodologyVersion } from "../domain/methodology.js";

export const METHODOLOGY_V1: MethodologyVersion = {
  versionId: "mw-v1",
  versionTag: "v1",
  isHumanApprovedBaseline: true,
  createdAt: "2026-09-22T00:00:00.000Z",
  activatedAt: "2026-09-22T00:00:00.000Z",
  dimensions: [
    {
      key: "market",
      name: "市场空间",
      description: "目标行业的可服务市场规模与结构",
      whyNeeded: "判断行业是否值得进入与投资体量",
      requiredInfo: "TAM/SAM/SOM、细分市场划分",
      confirmedCondition: "至少 1 条可溯源 TAM + 结构拆分",
      uncertainCondition: "仅有单一来源或口径不一致",
      unknownCondition: "无任何规模数据",
      weight: 0.1,
      criticality: "normal",
    },
    {
      key: "market_growth",
      name: "市场增速",
      description: "历史与预期增速",
      whyNeeded: "区分存量与增量",
      requiredInfo: "历史 CAGR、未来 3-5 年预期增速",
      confirmedCondition: "历史 + 预期均有来源",
      uncertainCondition: "仅历史或仅预期其一",
      unknownCondition: "无增速数据",
      weight: 0.08,
      criticality: "normal",
    },
    {
      key: "demand",
      name: "需求",
      description: "真实客户需求与采购意愿",
      whyNeeded: "验证需求是否真实、可持续",
      requiredInfo: "客户数、采购意愿、复购、真实订单",
      confirmedCondition: "有真实订单或一手客户证据",
      uncertainCondition: "仅有意向/访谈二手",
      unknownCondition: "无需求侧信息",
      weight: 0.1,
      criticality: "normal",
    },
    {
      key: "supply",
      name: "供给",
      description: "供给侧产能与成本曲线",
      whyNeeded: "判断供给约束与降本空间",
      requiredInfo: "产能、良率、BOM、成本下降曲线",
      confirmedCondition: "有产能/成本一手数据",
      uncertainCondition: "仅有估算",
      unknownCondition: "无供给数据",
      weight: 0.06,
      criticality: "normal",
    },
    {
      key: "competition",
      name: "竞争格局",
      description: "玩家、份额、壁垒",
      whyNeeded: "判断可切入性与护城河",
      requiredInfo: "company set、份额、集中度、壁垒",
      confirmedCondition: "份额 + 壁垒均有来源",
      uncertainCondition: "仅玩家名单无份额",
      unknownCondition: "无竞争信息",
      weight: 0.1,
      criticality: "normal",
    },
    {
      key: "technology",
      name: "技术成熟度",
      description: "技术路线与迭代风险",
      whyNeeded: "判断技术风险与代际替代",
      requiredInfo: "主流路线、里程碑、替代路线",
      confirmedCondition: "路线 + 里程碑有证据",
      uncertainCondition: "路线存在分歧",
      unknownCondition: "无技术信息",
      weight: 0.08,
      criticality: "normal",
    },
    {
      key: "industry_chain",
      name: "产业链",
      description: "上中下游结构与利润分配",
      whyNeeded: "定位价值环节与研究对象",
      requiredInfo: "上游/部件/整机/渠道/客户、利润分布",
      confirmedCondition: "链条完整 + 利润分配有证据",
      uncertainCondition: "链条有但利润分布缺失",
      unknownCondition: "无链条信息",
      weight: 0.07,
      criticality: "normal",
    },
    {
      key: "business_model",
      name: "商业模式",
      description: "如何收费与单位经济",
      whyNeeded: "判断变现路径",
      requiredInfo: "收费方式、客单价、毛利、留存",
      confirmedCondition: "单位经济有一手数据",
      uncertainCondition: "仅模式描述无数据",
      unknownCondition: "无模式信息",
      weight: 0.07,
      criticality: "normal",
    },
    {
      key: "profitability",
      name: "盈利能力",
      description: "行业/公司盈利质量",
      whyNeeded: "判断商业可持续性",
      requiredInfo: "毛利率、净利率、现金流",
      confirmedCondition: "多期财务数据",
      uncertainCondition: "单期或预测",
      unknownCondition: "无盈利数据",
      weight: 0.07,
      criticality: "normal",
    },
    {
      key: "policy",
      name: "政策环境",
      description: "监管与产业政策",
      whyNeeded: "判断政策风险与催化",
      requiredInfo: "鼓励/监管目录、补贴、牌照",
      confirmedCondition: "政策原文 + 时效",
      uncertainCondition: "仅转述",
      unknownCondition: "无政策信息",
      weight: 0.07,
      criticality: "normal",
    },
    {
      key: "risk",
      name: "风险",
      description: "技术/需求/政策/供应链风险",
      whyNeeded: "识别致命风险",
      requiredInfo: "主要风险事件 + 来源",
      confirmedCondition: "风险已识别并有缓解证据",
      uncertainCondition: "风险列举但未验证",
      unknownCondition: "无风险分析",
      weight: 0.1,
      criticality: "critical",
    },
    {
      key: "key_validation",
      name: "关键验证假设",
      description: "本行业最需一手验证的假设",
      whyNeeded: "指导尽调优先级",
      requiredInfo: "核心假设、验证方式、待验证问题",
      confirmedCondition: "假设已被一手证据验证",
      uncertainCondition: "假设列出但未验证",
      unknownCondition: "未识别关键假设",
      weight: 0.1,
      criticality: "critical",
    },
  ],
};
